
development:
  adapter: postgresql
  encoding: unicode
  database: proba
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: proba
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: proba
  pool: 5
  host: localhost

  